name: 'Setup Development Environment'
description: 'Sets up Python, PlatformIO, protobuf, and other development dependencies'

inputs:
  install-platformio:
    description: 'Install PlatformIO'
    required: false
    default: 'false'
  install-cmake:
    description: 'Install CMake'
    required: false
    default: 'false'
  install-clang-format:
    description: 'Install clang-format'
    required: false
    default: 'false'
  install-coverage-tools:
    description: 'Install lcov and gcc for coverage'
    required: false
    default: 'false'
  python-packages:
    description: 'Additional Python packages to install (space-separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip
    
    - name: Install PlatformIO
      if: inputs.install-platformio == 'true'
      shell: bash
      run: pip install platformio
    
    - name: Update apt cache
      shell: bash
      run: sudo apt-get update
    
    - name: Install protobuf and Abseil
      shell: bash
      run: sudo apt-get install -y protobuf-compiler libprotobuf-dev libabsl-dev
    
    - name: Install CMake
      if: inputs.install-cmake == 'true'
      shell: bash
      run: sudo apt-get install -y cmake
    
    - name: Install clang-format
      if: inputs.install-clang-format == 'true'
      shell: bash
      run: sudo apt-get install -y clang-format
    
    - name: Install coverage tools
      if: inputs.install-coverage-tools == 'true'
      shell: bash
      run: sudo apt-get install -y lcov gcc
    
    - name: Install additional Python packages
      if: inputs.python-packages != ''
      shell: bash
      run: pip install ${{ inputs.python-packages }}
    
    - name: Show protoc version
      shell: bash
      run: protoc --version
