name: Build and Push Docker Image

on:
  push:
    branches: ['dev', 'master']
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Convert repository owner to lowercase
        id: repo
        run: |
          echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
          echo "Repository owner (lowercase): ${GITHUB_REPOSITORY_OWNER,,}"
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.repo.outputs.owner }}/litepb-dev
          tags: |
            type=raw,value=latest
            type=sha,prefix=,format=long
          
      - name: Build and push Docker image
        id: build
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo.outputs.owner }}/litepb-dev:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.repo.outputs.owner }}/litepb-dev:buildcache,mode=max
          
      - name: Show image digest
        run: |
          echo "::notice::Image digest: ${{ steps.build.outputs.digest }}"
          echo "Image Digest: ${{ steps.build.outputs.digest }}"
          
      - name: Print pushed image tags
        run: |
          echo "::notice::Successfully pushed the following tags:"
          echo "Pushed Image Tags:"
          echo "${{ steps.meta.outputs.tags }}" | while IFS= read -r tag; do
            echo "  - $tag"
          done
